### ISSUE TITLE
Jenkins is insecure after initialization

### ISSUE THREAD

**Issue by surrettcharles** [surrettcharles/jenkins#5]
### Expected behavior
After starting a fresh image of Jenkins, the server should be secured.

### Actual behavior
New Jenkins instance allows anyone to do anything.

### steps to reproduce the issue
1. Start a new container
1. Open the Jenkins UI

**Comment by surrettcharles** [comment]
To be considered complete, should apply the following security:
- [x] Disable CLI access
- [x] Require login for any action other than viewing jobs
- [x] Provide a mechanism for supplying user credentials from a mounted volume
- [x] Configure CSRF to prevent XSS attacks

**Comment by surrettcharles** [comment]
Current build will configure GitHub OAuth based on values from a `security.yml` file. This file can be provided by a volume mounted to `/jenkins-config` in the container.
Example configuration file:
```yaml
---
OAUTH_SETTINGS:
    GITHUB_WEB_URI: 'https://github.com'
    GITHUB_API_URI: 'https://api.github.com'
    CLIENT_ID: 'your client id'
    CLIENT_SECRET: 'your secret'
    SCOPES: 'read:org'
SECURITY_GROUPS:
    # Users with similar permission needs should be grouped
    # into security groups. This can include GH users, teams,
    # orgs, and the anonymous/authenticated user
    - NAME: 'basic anonymous perms'
      PERMISSIONS:
        - 'hudson.model.Hudson.Read'
      USERS:
        - 'anonymous'
    - NAME: 'basic users'
      PERMISSIONS:
        - 'hudson.model.Hudson.Read'
        - 'hudson.model.Item.Build'
        - 'hudson.model.Item.Cancel'
        - 'hudson.model.View.Configure'
        - 'hudson.model.Item.Discover'
        - 'hudson.model.Item.Read'
        - 'hudson.model.View.Read'
        - 'hudson.model.View.Create'
      USERS:
        - 'authenticated'
    - NAME: 'jenkins admins'
      PERMISSIONS:
        - 'hudson.model.Computer.Build'
        - 'hudson.model.Computer.Configure'
        - 'hudson.model.Computer.Connect'
        - 'hudson.model.Computer.Create'
        - 'hudson.model.Computer.Delete'
        - 'hudson.model.Computer.Disconnect'
        - 'hudson.model.Hudson.Administer'
        - 'hudson.model.Hudson.ConfigureUpdateCenter'
        - 'hudson.model.Hudson.Read'
        - 'hudson.model.Hudson.RunScripts'
        - 'hudson.model.Hudson.UploadPlugins'
        - 'hudson.model.Item.Build'
        - 'hudson.model.Item.Cancel'
        - 'hudson.model.Item.Configure'
        - 'hudson.model.Item.Create'
        - 'hudson.model.Item.Delete'
        - 'hudson.model.Item.Discover'
        - 'hudson.model.Item.Read'
        - 'hudson.model.Item.Workspace'
        - 'hudson.model.Run.Delete'
        - 'hudson.model.Run.Update'
        - 'hudson.model.View.Configure'
        - 'hudson.model.View.Create'
        - 'hudson.model.View.Delete'
        - 'hudson.model.View.Read'
      USERS:
        - 'user1'
        - 'org*user2'
        - 'org*team'
```

**Comment by surrettcharles** [comment]
Will also examine disabling insecure protocols and remaining admin warnings issued by new Jenkins instance

**Comment by surrettcharles** [comment]
security items addressed, added script to configure system properties via `main_config.yml` file provided the same way as the `security.yml` file.
Example config file:
```yaml
---
MAIN:
    WORKSPACE_ROOT_DIR: '${JENKINS_HOME}/workspace/${ITEM_FULLNAME}-sample'
    BUILD_RECORD_ROOT_DIR: '${ITEM_ROOTDIR}/builds-sample'
    SYSTEM_MESSAGE: ''
    NUMBER_OF_EXECUTORS: 2
    LABELS:
        - "master-node"
        - "the-master-node"
    USAGE: 'EXCLUSIVE'
    QUIET_PERIOD: 10
    SCM_RETRY_COUNT: 15
    DISABLE_REMEMBER_ME: true
GLOBAL_PROPERTIES:
    ENVIRONMENT_VARIABLES:
        - NAME: 'VAR1'
          VALUE: 'HELLO'
        - NAME: 'VAR2'
          VALUE: 'WORLD'
    TOOL_LOCATIONS:
LOCATION:
    URL: 'http://localhost:8080'
    ADMIN_EMAIL: 'admin@localhost'
SHELL:
    EXECUTABLE: '/bin/sh'
```
